// Existence gate for 3D assets — manifest-first, fetch as dev-only fallback.
// Dependency-free apart from the generated manifest, imported relatively so
// the module stays unit-testable in plain Node (no JSX, no three.js,
// no path aliases).
//
// How it stays console-clean:
// - If the url is in the build-time manifest → 'ready', zero fetches.
// - If absent AND production → 'missing' immediately, zero fetches, hence
//   zero browser 404 lines (failed fetches are logged by the browser itself
//   and cannot be suppressed from JS — so we simply never request them).
// - If absent AND development → one cached HEAD fetch, so files dropped into
//   public/models mid-session still light up without a server restart
//   (at the cost of dev-only 404 lines, which never reach production).
//
// Convention: real models live at public/models/<name>.glb, served at
// runtime as /models/<name>.glb. The manifest is regenerated by
// scripts/generate-model-manifest.mjs on `npm run dev` / `npm run build`.
import { AVAILABLE_MODELS } from '../data/model-manifest.js';

const HEAD_CACHE = new Map(); // url -> Promise<'ready' | 'missing'>

/**
 * Resolve a model url to 'ready' | 'missing'. Never throws.
 * Results are cached per url for the session (single flight).
 */
export function checkModelAvailable(url) {
  if (!url) return Promise.resolve('missing');
  if (AVAILABLE_MODELS.includes(url)) return Promise.resolve('ready');
  if (process.env.NODE_ENV === 'production') return Promise.resolve('missing');
  if (!HEAD_CACHE.has(url)) {
    HEAD_CACHE.set(
      url,
      fetch(url, { method: 'HEAD' }).then(
        (res) => (res.ok ? 'ready' : 'missing'),
        () => 'missing'
      )
    );
  }
  return HEAD_CACHE.get(url);
}

/** For tests: reset the session HEAD cache. */
export function clearModelCheckCache() {
  HEAD_CACHE.clear();
}
