/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // AURA Dine palette (from Degine.md)
        primary: '#ffbe80',
        secondary: '#f5bc7c',
        tertiary: '#ffbe84',
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'on-surface': '#e5e2e1',
        'on-background': '#e5e2e1',
        'on-surface-variant': '#d6c3b4',
        'on-primary': '#4a2800',
        'on-primary-fixed': '#2d1600',
        'on-primary-fixed-variant': '#6a3b00',
        'on-primary-container': '#643800',
        'on-secondary': '#482a00',
        'on-secondary-fixed': '#2b1700',
        'on-secondary-fixed-variant': '#653e08',
        'on-secondary-container': '#e5ae6f',
        'on-tertiary': '#4b2700',
        'on-tertiary-fixed': '#2e1600',
        'on-tertiary-fixed-variant': '#6c3a00',
        'on-tertiary-container': '#663700',
        'primary-fixed': '#ffdcbf',
        'primary-fixed-dim': '#ffb872',
        'primary-container': '#e6a15c',
        'secondary-fixed': '#ffddba',
        'secondary-fixed-dim': '#f5bc7c',
        'secondary-container': '#67400a',
        'tertiary-fixed': '#ffdcc0',
        'tertiary-fixed-dim': '#ffb877',
        'tertiary-container': '#eaa05b',
        'surface-tint': '#ffb872',
        outline: '#9f8e80',
        'outline-variant': '#524439',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#885213',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
